# Generated by Django 3.0.8 on 2020-08-11 08:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dep_id', models.SmallIntegerField(primary_key=True, serialize=False, verbose_name='部門ID')),
                ('department', models.CharField(max_length=10, verbose_name='部門')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user_id', models.SmallIntegerField(primary_key=True, serialize=False, unique=True)),
                ('last_name_k', models.CharField(blank=True, max_length=30, verbose_name='姓（カタカナ）')),
                ('first_name_k', models.CharField(blank=True, max_length=30, verbose_name='名（カタカナ）')),
                ('last_name', models.CharField(max_length=15, verbose_name='姓')),
                ('first_name', models.CharField(max_length=15, verbose_name='名')),
                ('gender', models.BooleanField(default=0, verbose_name='性別')),
                ('birth',
                 models.DateField(default=datetime.datetime(1992, 8, 11, 17, 17, 5, 788285), verbose_name='生年月日')),
                ('nationality', models.CharField(blank=True, max_length=30, verbose_name='国籍')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='携帯電話')),
                ('postal_code', models.CharField(blank=True, max_length=15, verbose_name='郵便番号')),
                ('address1', models.CharField(blank=True, max_length=128, verbose_name='住所1')),
                ('address2', models.CharField(blank=True, max_length=128, verbose_name='住所2')),
                ('residence_card', models.CharField(blank=True, max_length=20, verbose_name='在留カード番号')),
                ('health_insurance', models.CharField(blank=True, max_length=20, verbose_name='健康保険番号')),
                ('department', models.CharField(max_length=20, verbose_name='部門')),
                ('emergency_contact_1_name', models.CharField(blank=True, max_length=30, verbose_name='緊急連絡先1_名前')),
                ('emergency_contact_1_relationship',
                 models.CharField(blank=True, max_length=10, verbose_name='緊急連絡先1_続柄')),
                ('emergency_contact_1_phone', models.CharField(blank=True, max_length=20, verbose_name='緊急連絡先1_電話番号')),
                ('emergency_contact_2_name', models.CharField(blank=True, max_length=30, verbose_name='緊急連絡先2_名前')),
                ('emergency_contact_2_relationship',
                 models.CharField(blank=True, max_length=10, verbose_name='緊急連絡先2_続柄')),
                ('emergency_contact_2_phone', models.CharField(blank=True, max_length=20, verbose_name='緊急連絡先2_電話番号')),
                ('emergency_contact_3_name', models.CharField(blank=True, max_length=30, verbose_name='緊急連絡先3_名前')),
                ('emergency_contact_3_relationship',
                 models.CharField(blank=True, max_length=10, verbose_name='緊急連絡先3_続柄')),
                ('emergency_contact_3_phone', models.CharField(blank=True, max_length=20, verbose_name='緊急連絡先3_電話番号')),
                ('delete', models.BooleanField(default=0, verbose_name='削除')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('create_id', models.CharField(max_length=20, verbose_name='作成者')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('update_id', models.CharField(max_length=20, verbose_name='更新者')),
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_id',
                                         to=settings.AUTH_USER_MODEL, verbose_name='ユーザーID')),
            ],
        ),
    ]
