# Generated by Django 3.0.8 on 2020-08-11 11:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('profile_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birth',
            field=models.DateField(default=datetime.datetime(1992, 8, 11, 20, 22, 23, 603283), verbose_name='生年月日'),
        ),
    ]
